### ISSUE TITLE
Why does it take too much time to Register or login?

### ISSUE THREAD

**Issue by just-injoey** [Priyanshu9898/Expense-Tracker-App#2]

**Comment by Priyanshu9898** [comment]
Hello Justin, 
Its because the backend of the  application is deployed on render free services. So when app is down for some time, it goes into the sleep state, when again user call the api, it runs the app and for which it can take 2-4 minutes. After that it can work smoothly.

**Comment by just-injoey** [comment]
Thanks Priyanshu, for your quick response👍
